apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: components
  contents:
  - path: main
    githubRelease:
      slug: petewall/eink-radiator
      latest: true
      disableAutoChecksumValidation: true
      assetNames: ["eink-radiator-arm6"]
  - path: ui
    git:
      url: https://github.com/petewall/eink-radiator
      ref: origin/main
      latest: true
      includePaths:
      - web/**/*
  - path: display
    git:
      url: https://github.com/petewall/eink-radiator-display
      ref: origin/main
  - path: image-source-blank
    githubRelease:
      slug: petewall/eink-radiator-image-source-blank
      latest: true
      disableAutoChecksumValidation: true
      assetNames: ["blank-arm6"]
  - path: image-source-image
    githubRelease:
      slug: petewall/eink-radiator-image-source-image
      latest: true
      disableAutoChecksumValidation: true
      assetNames: ["image-arm6"]
