apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: eink-radiator
  contents:
  - path: main
    githubRelease:
      slug: petewall/eink-radiator
      latest: true
      disableAutoChecksumValidation: true
  - path: display
    git:
      url: https://github.com/petewall/eink-radiator-display
      ref: origin/main
  - path: image-source-blank
    githubRelease:
      slug: petewall/eink-radiator-image-source-blank
      latest: true
      disableAutoChecksumValidation: true
  - path: image-source-image
    githubRelease:
      slug: petewall/eink-radiator-image-source-image
      latest: true
      disableAutoChecksumValidation: true
